<a href="https://colab.research.google.com/github/ShinWalnut/ABR_basic/blob/master/ABR_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np

In [13]:
gugu2 = np.array(list(map(int, input().split()))).reshape(-1,1)
gugu1 = np.arange(2,10).reshape(-1,1)
dan = np.arange(1,10).reshape(1,-1)

4 2 6 9


In [0]:
X=tf.placeholder(dtype=tf.float32, shape=(None,1), name="gugu")
Y=tf.constant(dan, dtype=tf.float32, name="dan")
gugudan = X*Y

In [15]:
with tf.Session() as sess:
  print("HW1-1 구구단\n", sess.run(gugudan, feed_dict={X: gugu1}))
  print("HW1-2 입력 한 수\n", sess.run(gugudan, feed_dict={X: gugu2}))

HW1-1 구구단
 [[ 2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 9. 18. 27. 36. 45. 54. 63. 72. 81.]]
HW1-2 입력 한 수
 [[ 4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 9. 18. 27. 36. 45. 54. 63. 72. 81.]]
